### ISSUE TITLE
UpdateBuilder zip bug

### ISSUE THREAD

**Issue by zenlor** [SKCraft/SKMCLauncher#53]
currently there is a bug with the Builder and pattern archive generation. It seems to be introduced in e21d6d5bf4651d04b8574234c0f47950d83b42e5 the jenkin build 52 exits with an error like:

```
[INFO] Writing ZIPs that are to be extracted later...
[INFO] -> mods/resources/ruins/taiga/oldfoundation.tml
Exception in thread "main" java.io.FileNotFoundException: .\out\mods\resources\r
uins\taiga\oldfoundation.tml (The system cannot find the path specified)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at com.sk89q.lpbuilder.ZipBucket.writeContents(ZipBucket.java:52)
        at com.sk89q.lpbuilder.UpdateBuilder.commitBuckets(UpdateBuilder.java:34
3)
        at com.sk89q.lpbuilder.UpdateBuilder.build(UpdateBuilder.java:377)
        at com.sk89q.lpbuilder.UpdateBuilder.build(UpdateBuilder.java:508)
        at com.sk89q.lpbuilder.UpdateBuilder.main(UpdateBuilder.java:611)
```

It will downcase all the files. The Exception is fixed in 39f5061 but it doesn't actually fix the zipping of files, it will write a manifest with all the files that should be zipped with it's original names. Of course, if you try to update your pack using the output as is won't find the requested files due to the case of the names (downcase).

I tested the builds using windows and JDK1.6 and 1.7 and under linux with 1.6

I'll provide a tree of the input/output folders and my builder_config.xml if needed

**Comment by sk89q** [comment]
Looks potentially related to #51.

**Comment by sk89q** [comment]
Is it possible to give me a bare minimum set of files that break?

**Comment by sk89q** [comment]
Fixed now, I believe.

#56 has reason
